[package]
name = "bhumi-terminal"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
description = "bhumi ui in terminal"
repository.workspace = true
rust-version.workspace = true

[dependencies]
crossterm.workspace = true
rapier3d = "0.30"
nalgebra = "0.30"
